# -*- coding: utf-8 -*-
"""sudoku to dimacs.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3J90D3wUW4yreagm8mx8RjlAy2JNt6Z
"""

def sudoku_to_DIMACS(sudoku, grid_size):
    clauses_DIMACS = []

    def var(x, y, k):
        return x * grid_size * grid_size + y * grid_size + k + 1

    # already filled cells
    for x in range(grid_size):
        for y in range(grid_size):
            if sudoku[x][y] != 0:
                k = sudoku[x][y] - 1
                clauses_DIMACS.append([var(x, y, k)])

    # enocde to DIMACS format
    total_variables = grid_size * grid_size * grid_size
    total_clauses = len(clauses_DIMACS)
    dimacs = f"p cnf {total_variables} {total_clauses}\n"
    for clause in clauses_DIMACS:
        dimacs += " ".join(map(str, clause)) + " 0\n"

    return dimacs